export const GET_REPORTS = 'GET_REPORTS'
export const ADD_REPORT = 'ADD_REPORT'
export const DELETE_REPORT = 'DELETE_REPORT'

export const REPORT_LOADING = 'REPORT_LOADING'
export const REPORT_LOADING_SUCCESS = 'REPORT_LOADING_SUCCESS'
export const REPORT_LOADING_FAIL = 'REPORT_LOADING_FAIL'

export const ADD_REPORT_START = 'ADD_REPORT_START'
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS'
export const ADD_REPORT_FAIL = 'ADD_REPORT_FAIL'
export const ADD_REPORT_FINISHED = 'ADD_REPORT_FINISHED'

export const ASSIGN_REPORT_START = 'ASSIGN_REPORT_START'
export const ASSIGN_REPORT_SUCCESS = 'ASSIGN_REPORT_SUCCESS'
export const ASSIGN_REPORT_FAIL = 'ASSIGN_REPORT_FAIL'
export const ASSIGN_REPORT_FINISHED = 'ASSIGN_REPORT_FINISH'

export const CLOSE_REPORT_START = 'CLOSE_REPORT_START'
export const CLOSE_REPORT_SUCCESS = 'CLOSE_REPORT_SUCCESS'
export const CLOSE_REPORT_FAIL = 'CLOSE_REPORT_FAIL'
export const CLOSE_REPORT_FINISH = 'CLOSE_REPORT_FINISH'

export const EDIT_REPORT_START = 'EDIT_REPORT_START'
export const EDIT_REPORT_SUCCESS = 'EDIT_REPORT_SUCCESS'
export const EDIT_REPORT_FAIL = 'EDIT_REPORT_FAIL'
export const EDIT_REPORT_FINISHED = 'EDIT_REPORT_FINISHED'

export const DELETE_REPORT_START = 'DELETE_REPORT_START'
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS'
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL'
export const DELETE_REPORT_FINISH = 'DELETE_REPORT_FINISH'

export const FETCH_REPORT_TO_EDIT = 'FETCH_REPORT_TO_EDIT'
// export const FETCH_REPORT_TO_EDIT_START = 'FETCH_REPORT_TO_EDIT_START'
// export const FETCH_REPORT_TO_EDIT_SUCCESS = 'FETCH_REPORT_TO_EDIT_SUCCESS'
// export const FETCH_REPORT_TO_EDIT_FAIL = 'FETCH_REPORT_TO_EDIT_FAIL'

export const INIT_APP_START = 'INIT_APP_START'
export const INIT_APP_FAIL = 'INIT_APP_FAIL'
export const INIT_APP_SUCCESS = 'INIT_APP_SUCCESS'

export const INIT_ASSIGN_REPORT_START = 'INIT_ASSIGN_REPORT_START'
export const INIT_ASSIGN_REPORT_FINISH = 'INIT_ASSIGN_REPORT_FINISH'

export const INIT_EDIT_REPORT_START = 'INIT_EDIT_REPORT_START'
export const INIT_EDIT_REPORT_FINISH = 'INIT_EDIT_REPORT_FINISH'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const GET_OWNER = 'GET_OWNER'
export const GET_OWNER_START = 'GET_OWNER_START'
export const GET_OWNER_FAIL = 'GET_OWNER_FAIL'
export const GET_OWNER_SUCCESS = 'GET_OWNER_SUCCESS'

export const GET_ROLE = 'GET_ROLE'
export const GET_ROLE_START = 'GET_ROLE_START'
export const GET_ROLE_FAIL = 'GET_ROLE_FAIL'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'